name: heart_flutter
description: Core flutter code & features shared between projects.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  heart:
    path: ../heart
  flutter:
    sdk: flutter
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
